### ISSUE TITLE
Worked Second Time: `block in <main>': undefined method `empty?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by HamishMacEwan** [hughdavenport/letsencrypt-iwantmyname-hook#5]
Worked fine for a number of renewals, but has just now:
```
 + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 500)

Details:
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;179&#46;5ea96068&#46;1498286951&#46;c12f117
</BODY></HTML>
/home/macewanh/bin/letsencrypt.sh/hooks/iwantmyname/iwantmyname-hook.rb:36:in `block in <main>': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/mechanize.rb:434:in `get'
	from /home/macewanh/bin/letsencrypt.sh/hooks/iwantmyname/iwantmyname-hook.rb:22:in `<main>'
```
Retried it and worked flawlessly... just in case you want to know.

**Comment by hughdavenport** [comment]
Hmm, will have to check whether that client is still using that. Thanks for the heads up

**Comment by hughdavenport** [comment]
FWIW, I'm now using dehydrated instead of letsencrypt.sh (fork I believe), but that client is now using just HTTP to verify, not the iwantmyname. I think I was about to do it for my email server, so might check that to reproduce :)

**Comment by HamishMacEwan** [comment]
```Splitting macewan.nz
Splitting nz
/home/macewanh/bin/letsencrypt.sh/hooks/iwantmyname/iwantmyname-hook.rb:36:in `block in <main>': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/mechanize.rb:434:in `get'
	from /home/macewanh/bin/letsencrypt.sh/hooks/iwantmyname/iwantmyname-hook.rb:22:in `<main>'
```
It's back and repeating the command doesn't solve it as described above.

If I correctly understand your above comment regarding dehydrated, that's using an http request to find something on the URL with the certificate?
